email_settings:
  sender_email: 1670074219@qq.com
  sender_password: yrcozxxcygqdbjjd
  smtp_port: 587
  smtp_server: smtp.qq.com

gpu_usage:
  219-216-99-133: {}
  219-216-101-107: {}
  219-216-99-5: {}
  219-216-99-6: {}
  219-216-99-7: {}
  219-216-99-10: {}

notification_settings:
  warning_threshold: 0.8

registry_server:
  host: 219.216.99.133
  registry_port: 5000
  password: siton@2024
  port: 22
  username: root

data_server:
  host: 219.216.99.133
  port: 22
  username: root
  password: siton@2024
  data_root: /data/user_data

servers:
  219-216-99-133:
    host: 219.216.99.133
    password: siton-2009
    port: 22
    username: root
  219-216-101-107:
    host: 219.216.101.107
    password: sitonholy@neu
    port: 22
    username: root
  219-216-99-5:
    host: 219.216.99.5
    password: sitonholy@neu
    port: 22
    username: root
  219-216-99-6:
    host: 219.216.99.6
    password: sitonholy@neu
    port: 22
    username: root
  219-216-99-7:
    host: 219.216.99.7
    password: sitonholy@neu
    port: 22
    username: root
  219-216-99-10:
    host: 219.216.99.10
    password: siton@2024
    port: 22
    username: root

task_records:

user_groups:
  admin_group:
    allowed_servers:
    - 219-216-99-133
    - 219-216-101-107
    - 219-216-99-5
    - 219-216-99-6
    - 219-216-99-7
    - 219-216-99-10
    description: 管理员用户组
    max_containers: 10
    max_gpus: 8
    name: 管理员组
    time_limit: 336
  default:
    allowed_servers:
    - 219-216-99-133
    - 219-216-101-107
    - 219-216-99-5
    - 219-216-99-6
    - 219-216-99-7
    - 219-216-99-10
    description: 默认用户组
    max_containers: 5
    max_gpus: 4
    name: 默认组
    time_limit: 18
  student_group:
    allowed_servers:
    - 219-216-99-133
    - 219-216-101-107
    description: 学生用户组
    max_containers: 3
    max_gpus: 2
    name: 学生组
    time_limit: 72
  
users:
  admin:
    data_dir: /nfs/data/admin
    email: 1670074219@qq.com
    group: admin_group
    password: q1w2e3az
    role: admin
    username: admin
  lanzetian:
    data_dir: /nfs/data/lanzetian
    email: 3439986898@qq.com
    password: q1w2e3az
    role: user
    username: lanzetian
  user1:
    data_dir: /nfs/data/user1
    email: 1670074219@qq.com
    group: student_group
    password: password1
    role: user
    username: user1
