docker_images:
- description: PyTorch 开发环境
  name: pytorch:latest
  registry: 实验室仓库
- description: TensorFlow 开发环境
  name: tensorflow:latest
  registry: 公共仓库
docker_registries:
- insecure: true
  name: 实验室仓库
  password: Sitonholy@2021
  url: 219.216.101.242:8888
  username: admin
- name: 公共仓库
  url: docker.io
registry_server:
  host: 219.216.101.242
  nfs_host: 219.216.101.242
  nfs_path: /nfs/data
  password: siton@2024
  port: 22
  registry_port: 8888
  username: root
servers:
  server1:
    host: 219.216.99.133
    password: siton-2009
    port: 22
    username: root
  server2:
    host: 219.216.99.4
    password: sitonholy@neu
    port: 22
    username: root
  server3:
    host: 219.216.99.5
    password: sitonholy@neu
    port: 22
    username: root
  server4:
    host: 219.216.99.6
    password: sitonholy@neu
    port: 22
    username: root
  server5:
    host: 219.216.99.7
    password: sitonholy@neu
    port: 22
    username: root
  server6:
    host: 219.216.99.10
    password: siton@2024
    port: 22
    username: root
users:
  admin:
    data_dir: ''
    password: admin_password
    role: admin
    username: admin
  lanzetian:
    data_dir: /nfs/data/lanzetian
    password: q1w2e3az
    role: user
    username: lanzetian
  user1:
    data_dir: /nfs/data/user1
    password: password1
    role: user
    username: user1
# 在config.yaml中添加任务记录部分
tasks:
  task_records: {}  # 用于存储所有任务记录
  user_limits:  # 用于存储用户使用限制
    default:  # 默认限制
      max_containers: 5  # 最大容器数
      max_gpus: 4  # 最大GPU数
      time_limit: 168  # 默认时间限制(小时)
