docker_images:
- description: PyTorch 开发环境
  name: pytorch:latest
  registry: 实验室仓库
- description: TensorFlow 开发环境
  name: tensorflow:latest
  registry: 公共仓库
docker_registries:
- insecure: true
  name: 实验室仓库
  password: Sitonholy@2021
  url: 219.216.101.242:8888
  username: admin
- name: 公共仓库
  url: docker.io
email_settings:
  sender_email: 1670074219@qq.com
  sender_password: yrcozxxcygqdbjjd
  smtp_port: 587
  smtp_server: smtp.qq.com
notification_settings:
  warning_threshold: 0.8
registry_server:
  host: 219.216.101.242
  nfs_host: 219.216.101.242
  nfs_path: /nfs/data
  password: siton@2024
  port: 22
  registry_port: 8888
  username: root
servers:
  server1:
    host: 219.216.99.133
    password: siton-2009
    port: 22
    username: root
  server2:
    host: 219.216.99.4
    password: sitonholy@neu
    port: 22
    username: root
  server3:
    host: 219.216.99.5
    password: sitonholy@neu
    port: 22
    username: root
  server4:
    host: 219.216.99.6
    password: sitonholy@neu
    port: 22
    username: root
  server5:
    host: 219.216.99.7
    password: sitonholy@neu
    port: 22
    username: root
  server6:
    host: 219.216.99.10
    password: siton@2024
    port: 22
    username: root
task_records:
  lanzetian:
  - container: lanzetian-server2-1731754425
    gpus:
    - '3'
    server: server2
    timestamp: 1731754437
  - container: lanzetian-server1-1731757717
    gpus:
    - '0'
    server: server1
    timestamp: 1731757719
  user1:
  - container: user1-server1-1731758194
    gpus:
    - '2'
    server: server1
    timestamp: 1731758210
user_groups:
  admin_group:
    name: "管理员组"
    description: "管理员用户组"
    allowed_servers: ["server1", "server2", "server3", "server4", "server5", "server6"]
    max_containers: 10
    max_gpus: 8
    time_limit: 336  # 小时
  default:
    name: "默认组"
    description: "默认用户组"
    allowed_servers: ["server1", "server2", "server3", "server4", "server5", "server6"]
    max_containers: 5
    max_gpus: 4
    time_limit: 168
  student_group:
    name: "学生组"
    description: "学生用户组"
    allowed_servers: ["server1", "server2"]
    max_containers: 3
    max_gpus: 2
    time_limit: 72
users:
  admin:
    username: admin
    password: admin_password
    role: admin
    group: admin_group
    email: 1670074219@qq.com
    data_dir: ''
  lanzetian:
    data_dir: /nfs/data/lanzetian
    email: 3439986898@qq.com
    password: q1w2e3az
    role: user
    username: lanzetian
  user1:
    username: user1
    password: password1
    role: user
    group: student_group
    email: 1670074219@qq.com
    data_dir: /nfs/data/user1
