docker_images:
- description: PyTorch 开发环境
  name: pytorch:latest
  registry: 实验室仓库
- description: TensorFlow 开发环境
  name: tensorflow:latest
  registry: 公共仓库
docker_registries:
- insecure: true
  name: 实验室仓库
  password: Sitonholy@2021
  url: 219.216.99.133:5000
  username: admin
- name: 公共仓库
  url: docker.io
email_settings:
  sender_email: 1670074219@qq.com
  sender_password: yrcozxxcygqdbjjd
  smtp_port: 587
  smtp_server: smtp.qq.com
gpu_usage:
  server1:
    '1': admin
    '2': user1
    '3': admin
  server2:
    '1': user1
    '2': admin
  server3: {}
  server4: {}
  server5: {}
  server6: {}
notification_settings:
  warning_threshold: 0.8
registry_server:
  host: 219.216.99.133
  nfs_host: 219.216.99.133
  nfs_path: /data/ftp_data
  password: siton@2024
  port: 22
  registry_port: 5000
  username: root
servers:
  server1:
    host: 219.216.99.133
    password: siton-2009
    port: 22
    username: root
  server2:
    host: 219.216.99.4
    password: sitonholy@neu
    port: 22
    username: root
  server3:
    host: 219.216.99.5
    password: sitonholy@neu
    port: 22
    username: root
  server4:
    host: 219.216.99.6
    password: sitonholy@neu
    port: 22
    username: root
  server5:
    host: 219.216.99.7
    password: sitonholy@neu
    port: 22
    username: root
  server6:
    host: 219.216.99.10
    password: siton@2024
    port: 22
    username: root
task_records:
  admin:
  - container: admin-server1-1731813354
    gpus:
    - '3'
    server: server1
    timestamp: 1731813357
  - container: admin-server2-1731813581
    gpus:
    - '2'
    server: server2
    timestamp: 1731813593
  - container: admin-server1-1731917332
    gpus:
    - '1'
    server: server1
    timestamp: 1731917336
  lanzetian: []
  user1:
  - container: user1-server1-1731758194
    gpus:
    - '2'
    server: server1
    timestamp: 1731758210
  - container: user1-server2-1731761915
    gpus:
    - '1'
    server: server2
    timestamp: 1731761927
user_groups:
  admin_group:
    allowed_servers:
    - server1
    - server2
    - server3
    - server4
    - server5
    - server6
    description: 管理员用户组
    max_containers: 10
    max_gpus: 8
    name: 管理员组
    time_limit: 336
  default:
    allowed_servers:
    - server1
    - server2
    - server3
    - server4
    - server5
    - server6
    description: 默认用户组
    max_containers: 5
    max_gpus: 4
    name: 默认组
    time_limit: 18
  student_group:
    allowed_servers:
    - server1
    - server2
    description: 学生用户组
    max_containers: 3
    max_gpus: 2
    name: 学生组
    time_limit: 72
users:
  admin:
    data_dir: /nfs/data/admin
    email: 1670074219@qq.com
    group: admin_group
    password: q1w2e3az
    role: admin
    username: admin
  lanzetian:
    data_dir: /nfs/data/lanzetian
    email: 3439986898@qq.com
    password: q1w2e3az
    role: user
    username: lanzetian
  user1:
    data_dir: /nfs/data/user1
    email: 1670074219@qq.com
    group: student_group
    password: password1
    role: user
    username: user1
