docker_images:
- description: PyTorch 开发环境
  name: pytorch:latest
  registry: 实验室仓库
- description: TensorFlow 开发环境
  name: tensorflow:latest
  registry: 公共仓库
docker_registries:
- insecure: true
  name: 实验室仓库
  password: Sitonholy@2021
  url: 219.216.101.242:8888
  username: admin
- name: 公共仓库
  url: docker.io
email_settings:
  sender_email: 1670074219@qq.com
  sender_password: yrcozxxcygqdbjjd
  smtp_port: 587
  smtp_server: smtp.qq.com
notification_settings:
  warning_threshold: 0.8
registry_server:
  host: 219.216.101.242
  nfs_host: 219.216.101.242
  nfs_path: /nfs/data
  password: siton@2024
  port: 22
  registry_port: 8888
  username: root
servers:
  server1:
    host: 219.216.99.133
    password: siton-2009
    port: 22
    username: root
  server2:
    host: 219.216.99.4
    password: sitonholy@neu
    port: 22
    username: root
  server3:
    host: 219.216.99.5
    password: sitonholy@neu
    port: 22
    username: root
  server4:
    host: 219.216.99.6
    password: sitonholy@neu
    port: 22
    username: root
  server5:
    host: 219.216.99.7
    password: sitonholy@neu
    port: 22
    username: root
  server6:
    host: 219.216.99.10
    password: siton@2024
    port: 22
    username: root
task_records:
  lanzetian:
  - container: lanzetian-server2-1731754425
    gpus:
    - '3'
    server: server2
    timestamp: 1731754437
tasks:
  task_records: {}
  user_limits:
    default:
      max_containers: 5
      max_gpus: 4
      time_limit: 1
users:
  admin:
    data_dir: ''
    email: 1670074219@qq.com
    password: admin_password
    role: admin
    username: admin
  lanzetian:
    data_dir: /nfs/data/lanzetian
    email: 3439986898@qq.com
    password: q1w2e3az
    role: user
    username: lanzetian
  user1:
    data_dir: /nfs/data/user1
    email: 1670074219@qq.com
    password: password1
    role: user
    username: user1
