docker_images:
- description: PyTorch 开发环境
  name: pytorch:latest
  registry: 实验室仓库
- description: TensorFlow 开发环境
  name: tensorflow:latest
  registry: 公共仓库
docker_registries:
- insecure: true
  name: 实验室仓库
  password: Sitonholy@2021
  url: 219.216.101.242:8888
  username: admin
- name: 公共仓库
  url: docker.io
registry_server:
  host: 219.216.101.242
  nfs_host: 219.216.101.242
  nfs_path: /nfs/data
  password: siton@2024
  port: 22
  registry_port: 8888
  username: root
servers:
  server1:
    host: 219.216.99.133
    password: siton-2009
    port: 22
    username: root
  server2:
    host: 219.216.99.4
    password: sitonholy@neu
    port: 22
    username: root
  server3:
    host: 219.216.99.5
    password: sitonholy@neu
    port: 22
    username: root
  server4:
    host: 219.216.99.6
    password: sitonholy@neu
    port: 22
    username: root
  server5:
    host: 219.216.99.7
    password: sitonholy@neu
    port: 22
    username: root
  server6:
    host: 219.216.99.10
    password: siton@2024
    port: 22
    username: root
task_records:
  lanzetian:
  - container: lanzetian-server2-1731734712
    gpus:
    - '3'
    - '4'
    - '5'
    server: server2
    timestamp: 1731734732
  - container: lanzetian-server1-1731735186
    gpus:
    - '4'
    server: server1
    timestamp: 1731735197
  - container: lanzetian-server1-1731736231
    gpus:
    - '4'
    server: server1
    timestamp: 1731736233
  - container: lanzetian-server1-1731736695
    gpus:
    - '4'
    server: server1
    timestamp: 1731736698
  - container: lanzetian-server1-1731737149
    gpus:
    - '5'
    server: server1
    timestamp: 1731737154
  - container: lanzetian-server2-1731737550
    gpus:
    - '2'
    server: server2
    timestamp: 1731737563
  - container: lanzetian-server2-1731754425
    gpus:
    - '3'
    server: server2
    timestamp: 1731754437
tasks:
  task_records: {}
  user_limits:
    default:
      max_containers: 5
      max_gpus: 4
      time_limit: 1
users:
  admin:
    data_dir: ''
    password: admin_password
    role: admin
    username: admin
    email: "1670074219@qq.com"
  lanzetian:
    data_dir: /nfs/data/lanzetian
    password: q1w2e3az
    role: user
    username: lanzetian
    email: "3439986898@qq.com"
  user1:
    data_dir: /nfs/data/user1
    password: password1
    role: user
    username: user1
    email: "1670074219@qq.com"

# 添加邮件配置
email_settings:
  smtp_server: "smtp.qq.com"  # 使用QQ邮箱的SMTP服务器
  smtp_port: 587
  sender_email: "1670074219@qq.com"  # 管理员邮箱
  sender_password: "yrcozxxcygqdbjjd"  # 邮箱授权码

# 添加提醒设置
notification_settings:
  warning_threshold: 0.8  # 当运行时间达到限制时间的80%时发送提醒
